language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install coverage nose coveralls
  - pip install .

script: nosetests --cover-package=amocrm_api

after_success:
  - coveralls
